2020/07/30 10:29:43 [emerg] 1#1: host not found in upstream "laravel" in /etc/nginx/conf.d/default.conf:18
2020/07/30 10:30:12 [emerg] 1#1: host not found in upstream "laravel" in /etc/nginx/conf.d/default.conf:18
2020/07/30 10:42:48 [emerg] 1#1: host not found in upstream "laravel" in /etc/nginx/conf.d/default.conf:18
2020/07/30 10:44:26 [error] 9#9: *2 "/var/www/public/index.php" is not found (2: No such file or directory), client: 172.20.0.1, server: _, request: "GET / HTTP/1.1", host: "localhost:445"
2020/07/30 10:44:28 [error] 9#9: *2 open() "/var/www/public/favicon.ico" failed (2: No such file or directory), client: 172.20.0.1, server: _, request: "GET /favicon.ico HTTP/1.1", host: "localhost:445", referrer: "http://localhost:445/"
2020/07/30 10:44:58 [error] 9#9: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "localhost:445"
2020/07/30 10:46:10 [error] 8#8: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "localhost:445"
2020/07/30 10:46:12 [error] 8#8: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "localhost:445"
2020/07/30 10:46:14 [error] 8#8: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "localhost:445"
2020/07/30 10:46:20 [error] 8#8: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "localhost:445"
2020/07/30 10:46:38 [error] 8#8: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 172.20.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "localhost:445"
2020/07/30 10:50:31 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://172.22.0.2:9000", host: "localhost:445"
2020/07/30 10:51:33 [error] 7#7: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://172.22.0.2:9000", host: "localhost:445"
2020/07/30 10:59:36 [error] 7#7: *2 "/var/www/public/index.php" is not found (2: No such file or directory), client: 172.23.0.1, server: _, request: "GET / HTTP/1.1", host: "localhost:445"
2020/07/30 10:59:39 [error] 7#7: *2 "/var/www/public/index.php" is not found (2: No such file or directory), client: 172.23.0.1, server: _, request: "GET / HTTP/1.1", host: "localhost:445"
2020/07/30 11:00:19 [error] 7#7: *2 "/var/www/public/index.php" is not found (2: No such file or directory), client: 172.23.0.1, server: _, request: "GET / HTTP/1.1", host: "localhost:445"
2020/07/30 11:03:36 [error] 7#7: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 172.23.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://172.23.0.2:9000", host: "localhost:445"
2020/07/30 11:06:07 [error] 7#7: *7 connect() failed (113: Host is unreachable) while connecting to upstream, client: 172.23.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://172.23.0.2:9000", host: "localhost:445"
2020/07/30 11:06:48 [error] 7#7: *7 connect() failed (113: Host is unreachable) while connecting to upstream, client: 172.23.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://172.23.0.2:9000", host: "localhost:445"
2020/07/30 11:26:17 [error] 6#6: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.25.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://172.25.0.2:9000", host: "localhost:445"
2020/07/30 13:33:09 [error] 10#10: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://172.26.0.2:9000", host: "localhost:445"
2020/07/30 13:36:13 [error] 10#10: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://172.26.0.2:9000", host: "localhost:445"
2020/07/30 13:36:32 [error] 10#10: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://172.26.0.2:9000", host: "localhost:445"
2020/07/30 13:38:35 [error] 10#10: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://172.26.0.2:9000", host: "localhost:445"
2020/07/30 13:38:39 [error] 10#10: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://172.26.0.2:9000", host: "localhost:445"
2020/07/30 13:39:14 [error] 10#10: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://172.26.0.2:9000", host: "localhost:445"
2020/07/30 13:40:15 [error] 10#10: *10 connect() failed (111: Connection refused) while connecting to upstream, client: 172.26.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://172.26.0.2:9000", host: "localhost:445"
2020/07/30 13:41:50 [error] 10#10: *17 connect() failed (113: Host is unreachable) while connecting to upstream, client: 172.26.0.1, server: _, request: "GET / HTTP/1.1", upstream: "fastcgi://172.26.0.2:9000", host: "localhost:445"
2020/07/31 07:56:30 [emerg] 1#1: invalid URL prefix in /etc/nginx/conf.d/default.conf:38
2020/07/31 07:57:36 [emerg] 1#1: invalid URL prefix in /etc/nginx/conf.d/default.conf:38
2020/07/31 08:01:40 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: _, request: "GET / HTTP/1.1", upstream: "http://0.0.0.0:8000/", host: "localhost:446"
2020/07/31 08:01:42 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: _, request: "GET /favicon.ico HTTP/1.1", upstream: "http://0.0.0.0:8000/favicon.ico", host: "localhost:446", referrer: "http://localhost:446/"
2020/07/31 08:02:02 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: _, request: "GET / HTTP/1.1", upstream: "http://0.0.0.0:8000/", host: "localhost:446"
2020/07/31 08:02:02 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: _, request: "GET /favicon.ico HTTP/1.1", upstream: "http://0.0.0.0:8000/favicon.ico", host: "localhost:446", referrer: "http://localhost:446/"
2020/07/31 08:02:14 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: _, request: "GET / HTTP/1.1", upstream: "http://0.0.0.0:8000/", host: "localhost:446"
2020/07/31 08:02:14 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: _, request: "GET /favicon.ico HTTP/1.1", upstream: "http://0.0.0.0:8000/favicon.ico", host: "localhost:446", referrer: "http://localhost:446/"
2020/07/31 08:02:15 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: _, request: "GET / HTTP/1.1", upstream: "http://0.0.0.0:8000/", host: "localhost:446"
2020/07/31 08:02:15 [error] 6#6: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.27.0.1, server: _, request: "GET /favicon.ico HTTP/1.1", upstream: "http://0.0.0.0:8000/favicon.ico", host: "localhost:446", referrer: "http://localhost:446/"
2020/07/31 08:04:03 [error] 10#10: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: _, request: "GET / HTTP/1.1", upstream: "http://172.28.0.4:8000/", host: "localhost:446"
2020/07/31 08:04:04 [error] 10#10: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: _, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.4:8000/favicon.ico", host: "localhost:446", referrer: "http://localhost:446/"
2020/07/31 08:16:58 [emerg] 1#1: host not found in upstream "client:8080" in /etc/nginx/conf.d/default.conf:9
2020/07/31 08:18:37 [error] 9#9: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: _, request: "GET / HTTP/1.1", upstream: "http://172.28.0.5:8080/", host: "localhost:447"
2020/07/31 08:18:38 [error] 9#9: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.28.0.1, server: _, request: "GET /favicon.ico HTTP/1.1", upstream: "http://172.28.0.5:8080/favicon.ico", host: "localhost:447", referrer: "http://localhost:447/"
2020/07/31 08:19:42 [emerg] 1#1: host not found in upstream "client:3000" in /etc/nginx/conf.d/default.conf:9
2020/07/31 08:36:29 [emerg] 1#1: host not found in upstream "client:3000" in /etc/nginx/conf.d/default.conf:9
2020/07/31 08:39:20 [emerg] 1#1: invalid number of arguments in "proxy_set_header" directive in /etc/nginx/conf.d/default.conf:61
2020/07/31 08:39:49 [emerg] 1#1: invalid number of arguments in "proxy_set_header" directive in /etc/nginx/conf.d/default.conf:59
